import { Schema, model, InferSchemaType } from "mongoose";

const eventSchema = new Schema(
  {
    // Anonymous browser-tab session identifier generated by tracker.js
    sessionId: {
      type: String,
      required: true,
      index: true,
    },

    // Base event category.
    // page_view = automatic page load
    // click = raw heatmap click or structured funnel action
    eventType: {
      type: String,
      required: true,
      enum: ["page_view", "click"],
      index: true,
    },

    // Structured event name.
    // Examples:
    // product_viewed, add_to_bag, payment_selected, order_confirmed.
    eventName: {
      type: String,
      default: "",
      index: true,
    },

    // true = meaningful funnel event
    // false = raw click recorded for heatmap rendering
    funnelEvent: {
      type: Boolean,
      default: false,
      index: true,
    },

    // Flexible structured metadata supplied by the demo storefront.
    // Examples:
    // {
    //   productId: "arc-lamp",
    //   productName: "Arc Lamp",
    //   category: "home",
    //   price: 84,
    //   quantity: 1,
    //   paymentMethod: "upi",
    //   deliveryDays: 2,
    //   orderValue: 176
    // }
    properties: {
      type: Schema.Types.Mixed,
      default: {},
    },

    // Browser and page context
    pageUrl: {
      type: String,
      required: true,
      index: true,
    },

    path: {
      type: String,
      default: "",
      index: true,
    },

    pageTitle: {
      type: String,
      default: "",
    },

    referrer: {
      type: String,
      default: "",
    },

    userAgent: {
      type: String,
      default: "",
    },

    timestamp: {
      type: Date,
      required: true,
      default: Date.now,
      index: true,
    },

    // Click coordinates. Used only for raw_click / heatmap events.
    x: {
      type: Number,
      default: null,
    },

    y: {
      type: Number,
      default: null,
    },

    viewportWidth: {
      type: Number,
      default: null,
    },

    viewportHeight: {
      type: Number,
      default: null,
    },
  },
  {
    versionKey: false,
  }
);

// Session journey query
eventSchema.index({ sessionId: 1, timestamp: 1 });

// Page-level heatmap and page analytics queries
eventSchema.index({
  pageUrl: 1,
  eventType: 1,
  funnelEvent: 1,
  timestamp: 1,
});

// Funnel aggregation queries
eventSchema.index({
  funnelEvent: 1,
  eventName: 1,
  timestamp: 1,
});

// Event debugging / event stream queries
eventSchema.index({
  eventName: 1,
  timestamp: -1,
});

export type EventDoc = InferSchemaType<typeof eventSchema>;

export default model("Event", eventSchema);