import { Schema, model, InferSchemaType } from "mongoose";

const sessionSchema = new Schema(
  {
    // Anonymous session identifier generated by demo/tracker.js
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // First and most recent activity timestamps
    firstSeen: {
      type: Date,
      required: true,
      index: true,
    },

    lastSeen: {
      type: Date,
      required: true,
      index: true,
    },

    // Fast dashboard-level counters
    totalEvents: {
      type: Number,
      default: 0,
    },

    pageViews: {
      type: Number,
      default: 0,
    },

    clicks: {
      type: Number,
      default: 0,
    },

    // Entry and latest page information
    firstPageUrl: {
      type: String,
      default: "",
    },

    lastPageUrl: {
      type: String,
      default: "",
    },

    lastEventType: {
      type: String,
      default: "",
    },

    // Browser context retained from latest received event
    userAgent: {
      type: String,
      default: "",
    },

    referrer: {
      type: String,
      default: "",
    },
  },
  {
    versionKey: false,
  }
);

// Used by GET /api/sessions to show recent visitor sessions.
sessionSchema.index({ lastSeen: -1 });

// Useful for date-based reporting and future retention/deletion jobs.
sessionSchema.index({ firstSeen: -1 });

export type SessionDoc = InferSchemaType<typeof sessionSchema>;

export default model("Session", sessionSchema);